version: '2'
services:
  stubby:
    image: "dot-stubby:local"
    container_name: stubby
    restart: unless-stopped
  unbound:
    image: "dot-unbound:local"
    container_name: unbound
    restart: unless-stopped
    depends_on:
      - "stubby"
    ports:
     - "53:53/udp"
    volumes:
      - ./unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
